[package]
name = "conductor"
version = "0.1.0"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.12.1"
indexmap = "1.5.0"
lewton = "0.10.1"
ringbuf = "0.2.2"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false
